spring.datasource.url = jdbc:mysql://data-base-libros-avilaramirezluiseduardo1-aa41.d.aivencloud.com:28453/Database_Clinica

spring.datasource.username =  David
spring.datasource.password = AVNS_o5MFw9o8l5LLBP4WoML

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.format_sql = true

email.username = avilaramirezluiseduardo1@gmail.com
password.username = segfroseokampenu